version: "3.8"

services:
  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ku9456123
      MYSQL_DATABASE: SEP490
      MYSQL_USER: edward
      MYSQL_PASSWORD: ku9456123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network: