name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Checkout code 
    
    - uses: docker/setup-buildx-action@v1
    - name: Setup Docker Build 

    - uses: docker/login-action@v4
    - name: Login to Docker Hub
      with:
        username: ${{ }}
        password: ${{ }}

    - uses: docker/build-push-action@v2
    - name: Build and push the Docker image
      with:
        context: .
        push: true
        tags: edward2k2/sep490_backend:latest
        
